version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mlp_app
    container_name: mlp_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - default
  db:
    image: mysql:8.0
    container_name: mlp_app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mlp_database
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - default
    ports:
      - 3306:3306
  nginx:
    image: nginx:alpine
    container_name: mlp_app_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - default
networks:
  default:
    driver: bridge
